// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-kxMzN8AY8AphJ1V4_w0NNn7VjWwLzc',
    appId: '1:157926434798:web:ed4f38e6b5386d7d3dd0ff',
    messagingSenderId: '157926434798',
    projectId: 'chatbot-rgt-week6',
    authDomain: 'chatbot-rgt-week6.firebaseapp.com',
    storageBucket: 'chatbot-rgt-week6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeFbMO7aYjC6I0xN0VNyHFC1kFpyXA1Fw',
    appId: '1:157926434798:android:e1bb8766bca09c513dd0ff',
    messagingSenderId: '157926434798',
    projectId: 'chatbot-rgt-week6',
    storageBucket: 'chatbot-rgt-week6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoaewQ4dKFLIka7ZmtBTSeUtFdofp1ATc',
    appId: '1:157926434798:ios:198555e8052fcf9e3dd0ff',
    messagingSenderId: '157926434798',
    projectId: 'chatbot-rgt-week6',
    storageBucket: 'chatbot-rgt-week6.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoaewQ4dKFLIka7ZmtBTSeUtFdofp1ATc',
    appId: '1:157926434798:ios:198555e8052fcf9e3dd0ff',
    messagingSenderId: '157926434798',
    projectId: 'chatbot-rgt-week6',
    storageBucket: 'chatbot-rgt-week6.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe-kxMzN8AY8AphJ1V4_w0NNn7VjWwLzc',
    appId: '1:157926434798:web:5086c2743c6078103dd0ff',
    messagingSenderId: '157926434798',
    projectId: 'chatbot-rgt-week6',
    authDomain: 'chatbot-rgt-week6.firebaseapp.com',
    storageBucket: 'chatbot-rgt-week6.firebasestorage.app',
  );
}
